# Generated by Django 5.1.3 on 2025-01-11 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('search_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('results_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-search_time'],
            },
        ),
    ]
